name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Check formatting with black
      run: black --check sidecar_eq tests
    
    - name: Lint with ruff
      run: ruff check sidecar_eq tests
    
    - name: Type check with mypy
      run: mypy sidecar_eq
      continue-on-error: true  # Don't fail build on type errors yet
    
    - name: Run tests
      run: pytest tests/ -v
      env:
        QT_QPA_PLATFORM: offscreen  # Run Qt tests headless
